### ISSUE TITLE
Envoy configuration issues

### ISSUE THREAD

**Issue by WojciechZankowski** [juliusz-cwiakalski/grpc-angular-spring-boot-demo#3]
I am not sure if I use different envoy version, but your configuration is not working on my machine: 

1) "use_websocket" parameter is unknown
2) I got an issue that envoy.router filter needs to be terminal 
3) envoy.buffer config is throwing unknown field exceptions

After couple tweaks this works for me:

```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 8081 }

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 8080 }
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                upgrade_configs:
                  - upgrade_type: websocket
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ['*']
                      routes:
                        - match: { prefix: '/pl.jcw' }
                          route:
                            cluster: chat_backend_service
                            max_grpc_timeout: 0s
                        - match: { regex: '^(?!pl.jcw).*$' }
                          route:
                            {
                              #use_websocket: true,
                              host_rewrite: localhost,
                              cluster: service_frontend,
                            }
                      cors:
                        allow_origin:
                          - '*'
                        allow_methods: GET, PUT, DELETE, POST, OPTIONS
                        allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                        max_age: '1728000'
                        expose_headers: custom-header-1,grpc-status,grpc-message
                http_filters:
                  - name: envoy.grpc_web
                  - name: envoy.cors
                  - name: envoy.buffer
                    config:
                      #max_request_bytes: 100000
                      #max_request_time: 36s
                  - name: envoy.router
  clusters:
    - name: chat_backend_service
      connect_timeout: 0.25s
      type: logical_dns
      http2_protocol_options: {}
      lb_policy: round_robin
      hosts: [{ socket_address: { address: chat-backend, port_value: 6565 } }]
    - name: service_frontend
      connect_timeout: 1s
      type: LOGICAL_DNS
      lb_policy: ROUND_ROBIN
      hosts: [{ socket_address: { address: chat-webapp, port_value: 4200 } }]

```
